### ISSUE TITLE
c.country laos doesn't result in any response

### ISSUE THREAD

**Issue by LuminarySage** [Tetracyl/CoronaCord#5]

**Comment by 3eif** [comment]
Laos is labeled as "Lao People's Democratic Republic" which is why simply typing "c.country Laos" did not work. I managed to fix this though by making it an alias of the original country name.

Both of these commands should work now:
> c.country Laos
> c.country Lao People's Democratic Republic
![image](https://user-images.githubusercontent.com/29833473/80323076-f4096500-87dd-11ea-82d5-a9385af55912.png)

Thank you for bringing this issue to my attention. If you have any other issues please report them!
